In [40]:
import pandas as pd

In [41]:
df_books = pd.read_csv('./bestsellers-with-categories.csv',sep=",",header=0)
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [42]:
mayor_2016 = df_books['Year'] > 2016

In [43]:
df_books[mayor_2016]

,Name,Author,User Rating,Reviews,Price,Year,Genre
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
...,...,...,...,...,...,...,...
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [44]:
genre_fiction = df_books['Genre']=='Fiction'

In [45]:
df_books[mayor_2016 & genre_fiction]

,Name,Author,User Rating,Reviews,Price,Year,Genre
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
13,A Wrinkle in Time (Time Quintet),Madeleine L'Engle,4.5,5153,5,2018,Fiction
40,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,14344,5,2017,Fiction
...,...,...,...,...,...,...,...
509,To Kill a Mockingbird,Harper Lee,4.8,26234,7,2019,Fiction
529,What Should Danny Do? (The Power to Choose Ser...,Adir Levy,4.8,8170,13,2019,Fiction
534,Where the Crawdads Sing,Delia Owens,4.8,87841,15,2019,Fiction
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction

In [46]:
df_books[~mayor_2016 & ~genre_fiction]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,2,2010,Non Fiction
12,A Stolen Life: A Memoir,Jaycee Dugard,4.6,4149,32,2011,Non Fiction
14,"Act Like a Lady, Think Like a Man: What Men Re...",Steve Harvey,4.6,5013,17,2009,Non Fiction
15,Adult Coloring Book Designs: Stress Relief Col...,Adult Coloring Book Designs,4.5,2313,4,2016,Non Fiction
...,...,...,...,...,...,...,...
532,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",William Davis,4.4,7497,6,2013,Non Fiction
533,When Breath Becomes Air,Paul Kalanithi,4.8,13779,14,2016,Non Fiction
537,Wild: From Lost to Found on the Pacific Crest ...,Cheryl Strayed,4.4,17044,18,2012,Non Fiction
539,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,4.2,1302,11,2010,Non Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction

In [47]:
df_books[(df_books['Year'] > 2016) & (df_books['Genre']=='Fiction')]

,Name,Author,User Rating,Reviews,Price,Year,Genre
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
13,A Wrinkle in Time (Time Quintet),Madeleine L'Engle,4.5,5153,5,2018,Fiction
40,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,14344,5,2017,Fiction
...,...,...,...,...,...,...,...
509,To Kill a Mockingbird,Harper Lee,4.8,26234,7,2019,Fiction
529,What Should Danny Do? (The Power to Choose Ser...,Adir Levy,4.8,8170,13,2019,Fiction
534,Where the Crawdads Sing,Delia Owens,4.8,87841,15,2019,Fiction
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction

In [48]:
df_books[df_books['Author'].str.contains('Davis')]

,Name,Author,User Rating,Reviews,Price,Year,Genre
531,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",William Davis,4.4,7497,6,2012,Non Fiction
532,"Wheat Belly: Lose the Wheat, Lose the Weight, ...",William Davis,4.4,7497,6,2013,Non Fiction

In [49]:
df_books[df_books['Year'].isin([2016,2017])]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
...,...,...,...,...,...,...,...
533,When Breath Becomes Air,Paul Kalanithi,4.8,13779,14,2016,Non Fiction
543,Wonder,R. J. Palacio,4.8,21625,9,2016,Fiction
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction

In [50]:
df_books[df_books['Year'].between(2016,2017)]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
...,...,...,...,...,...,...,...
533,When Breath Becomes Air,Paul Kalanithi,4.8,13779,14,2016,Non Fiction
543,Wonder,R. J. Palacio,4.8,21625,9,2016,Fiction
544,Wonder,R. J. Palacio,4.8,21625,9,2017,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction

In [51]:
df_books[df_books['Year'].eq(2016)]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction
15,Adult Coloring Book Designs: Stress Relief Col...,Adult Coloring Book Designs,4.5,2313,4,2016,Non Fiction
19,Alexander Hamilton,Ron Chernow,4.8,9198,13,2016,Non Fiction
36,Between the World and Me,Ta-Nehisi Coates,4.7,10070,13,2016,Non Fiction
37,Born to Run,Bruce Springsteen,4.7,3729,18,2016,Non Fiction
43,Calm the F*ck Down: An Irreverent Adult Colori...,Sasha O'Hara,4.6,10369,4,2016,Non Fiction
49,Cravings: Recipes for All the Food You Want to...,Chrissy Teigen,4.7,4761,16,2016,Non Fiction
64,Dear Zoo: A Lift-the-Flap Book,Rod Campbell,4.8,10922,5,2016,Fiction
88,Double Down (Diary of a Wimpy Kid #11),Jeff Kinney,4.8,5118,20,2016,Fiction
100,Fahrenheit 451,Ray Bradbury,4.6,10721,8,2016,Fiction
102,Fantastic Beasts and Where to Find Them: The O...,J.K. Rowling,4.7,4370,15,2016,Fiction
112,First 100 Words,Roger Priddy,4.7,17323,4,2016,Non Fiction
124,Giraffes Can't Dance,Giles Andreae,4.8,14038,4,2016,Fiction
151,Hamilton: The Revolution,Lin-Manuel Miranda,4.9,5867,54,2016,Non Fiction
153,Harry Potter and the Chamber of Secrets: The I...,J.K. Rowling,4.9,19622,30,2016,Fiction
154,"Harry Potter and the Cursed Child, Parts 1 & 2...",J.K. Rowling,4.0,23973,12,2016,Fiction
157,Harry Potter and the Sorcerer's Stone: The Ill...,J.K. Rowling,4.9,10052,22,2016,Fiction
159,Harry Potter Paperback Box Set (Books 1-7),J. K. Rowling,4.8,13471,52,2016,Fiction
163,Hillbilly Elegy: A Memoir of a Family and Cult...,J. D. Vance,4.4,15526,14,2016,Non Fiction
168,How to Win Friends & Influence People,Dale Carnegie,4.7,25001,11,2016,Non Fiction
192,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,4.9,19576,8,2016,Non Fiction
202,Killing the Rising Sun: How America Vanquished...,Bill O'Reilly,4.8,8916,6,2016,Non Fiction
211,Laugh-Out-Loud Jokes for Kids,Rob Elliott,4.6,6990,4,2016,Non Fiction
229,Milk and Honey,Rupi Kaur,4.7,17739,8,2016,Non Fiction
235,Mindset: The New Psychology of Success,Carol S. Dweck,4.6,5542,10,2016,Non Fiction
242,Night (Night),Elie Wiesel,4.7,5178,9,2016,Non Fiction
249,"Oh, the Places You'll Go!",Dr. Seuss,4.9,21834,8,2016,Fiction
268,Pokémon Deluxe Essential Handbook: The Need-to...,Scholastic,4.7,3503,9,2016,Fiction
278,Publication Manual of the American Psychologic...,American Psychological Association,4.5,8580,46,2016,Non Fiction
311,StrengthsFinder 2.0,Gallup,4.0,5069,17,2016,Non Fiction
326,The 5 Love Languages: The Secret to Love that ...,Gary Chapman,4.8,25554,8,2016,Non Fiction
336,The 7 Habits of Highly Effective People: Power...,Stephen R. Covey,4.7,4725,16,2016,Non Fiction
358,The Constitution of the United States,Delegates of the Constitutional,4.8,2774,0,2016,Non Fiction
377,The Four Agreements: A Practical Guide to Pers...,Don Miguel Ruiz,4.7,23308,6,2016,Non Fiction
383,The Girl on the Train,Paula Hawkins,4.1,79446,7,2016,Fiction
390,The Going-To-Bed Book,Sandra Boynton,4.8,5249,5,2016,Fiction
424,The Life-Changing Magic of Tidying Up: The Jap...,Marie Kondō,4.5,22641,11,2016,Non Fiction
431,The Magnolia Story,Chip Gaines,4.9,7861,5,2016,Non Fiction
438,The Nightingale: A Novel,Kristin Hannah,4.8,49288,11,2016,Fiction
444,"The Official SAT Study Guide, 2016 Edition (Of...",The College Board,4.3,807,36,2016,Non Fiction
479,The Very Hungry Caterpillar,Eric Carle,4.9,19546,5,2016,Fiction
484,The Whole30: The 30-Day Guide to Total Health ...,Melissa Hartwig Urban,4.6,7508,16,2016,Non Fiction
486,The Wonderful Things You Will Be,Emily Winfield Martin,4.9,8842,10,2016,Fiction
502,Thug Kitchen: The Official Cookbook: Eat Like ...,Thug Kitchen,4.6,11128,23,2016,Non Fiction
508,To Kill a Mockingbird,Harper Lee,4.8,26234,0,2016,Fiction
523,Uninvited: Living Loved When You Feel Less Tha...,Lysa TerKeurst,4.7,4585,9,2016,Non Fiction
533,When Breath Becomes Air,Paul Kalanithi,4.8,13779,14,2016,Non Fiction
543,Wonder,R. J. Palacio,4.8,21625,9,2016,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction